default: &default
  adapter: postgresql
  encoding: unicode
  pool: 15

development:
  <<: *default
  host: localhost
  database: anxious_panda_development

production:
  <<: *default
  host: <%= ENV.fetch('AWS_RDS_HOST', 'placeholder_host') %>
  username: <%= ENV.fetch('AWS_RDS_USERNAME', 'placeholder_user') %>
  password: <%= ENV.fetch('AWS_RDS_PASSWORD', 'placeholder_password') %>
  database: <%= ENV.fetch('AWS_RDS_NAME', 'placeholder_database') %>
  port: <%= ENV.fetch('AWS_RDS_PORT', 5432) %>

test:
  <<: *default
  database: anxious_panda_test
  timeout: 5000
